# version is now obsolete
version: '3'

services:
  db:
    image: mongo
    restart: always
    ports: # expose ports in “host:container” format
      - 27017:27017
    environment: #env variables to pass into the container
      MONGODB_DATABASE: ${MONGODB_NAME} # DB name as per the environment file
